import os
from google import genai
from mitre_mapper import MitreMapper
from dotenv import load_dotenv


class AIForensicEngine:
    def __init__(self):
        self.model_name = "Sentinel-AI v3.0 (SOC Core)"
        self.mitre = MitreMapper()

        load_dotenv()
        api_key = os.getenv("GEMINI_API_KEY")
        if api_key and len(api_key) > 10:
            try:
                self.client = genai.Client(api_key=api_key)
                self.is_active = True
            except Exception:
                self.client = None
                self.is_active = False
        else:
            self.client = None
            self.is_active = False

    def _generate_fallback_report(self, event_data: dict) -> str:
        """Generate a professional forensic report based on event data and MITRE ATT&CK."""
        process  = event_data.get("process_name", "Unknown")
        cmd      = event_data.get("command_line", "") or ""
        user     = event_data.get("user", "unknown")
        score    = event_data.get("anomaly_score", 0.0)
        severity = event_data.get("severity", "normal").lower()

        techniques = self.mitre.get_attack_info(cmd)

        severity_map = {
            "critical": ("CRITICAL",  "immediate containment and isolation", "ISOLATE"),
            "high":     ("HIGH",      "urgent investigation",                "BLOCK"),
            "medium":   ("MEDIUM",    "active monitoring",                   "MONITOR"),
            "low":      ("LOW",       "routine review",                      "REVIEW"),
            "normal":   ("NORMAL",    "standard logging",                    "ALLOW"),
        }
        sev_label, sev_action, sev_verdict = severity_map.get(severity, severity_map["normal"])

        lines = []
        lines.append(f"SENTINEL-AI FORENSIC REPORT  |  Sentinel-AI v3.0")
        lines.append(f"Status: {sev_label}  |  Verdict: {sev_verdict}")
        lines.append("")
        lines.append(f"Process:    {process}  (user: {user})")
        if cmd:
            preview = cmd[:140] + ("..." if len(cmd) > 140 else "")
            lines.append(f"Command:    {preview}")
        threshold_note = "exceeds anomaly threshold" if score > 0.35 else "within normal baseline"
        lines.append(f"ML Score:   {score:.4f}  ({threshold_note})")
        lines.append("")

        if techniques:
            lines.append("MITRE ATT&CK Techniques Detected")
            lines.append("-" * 36)
            for t in techniques:
                lines.append(f"  {t['technique']}  {t['name']}")
                desc = t.get("description", "Technique associated with unauthorized access or code execution.")
                lines.append(f"  {desc}")
                if t.get("remediation"):
                    lines.append(f"  Countermeasure: {t['remediation']}")
                lines.append("")

            lines.append("Analyst Verdict")
            lines.append("-" * 36)
            tech_names = ", ".join(t["name"] for t in techniques)
            lines.append(
                f"Activity consistent with {tech_names} patterns was detected. "
                f"Process '{process}' was initiated by '{user}' with an anomaly score of {score:.4f}. "
                f"Action required: {sev_action}."
            )
        else:
            lines.append("Analyst Verdict")
            lines.append("-" * 36)
            if score > 0.35:
                lines.append(
                    f"Process '{process}' exhibits statistically anomalous behaviour "
                    f"(score: {score:.4f}) deviating from the established baseline. "
                    f"No known MITRE ATT&CK technique match was found, however "
                    f"the behavioural profile warrants {sev_action}."
                )
            else:
                lines.append(
                    f"Process '{process}' is operating within normal parameters. "
                    f"Anomaly score ({score:.4f}) is below the detection threshold. "
                    f"No threat indicators detected."
                )

        lines.append("")
        lines.append("---")
        lines.append("Report generated by Sentinel-AI  |  Isolation Forest ML + MITRE ATT&CK KB")
        return "\n".join(lines)

    def analyze_event(self, event_data: dict) -> str:
        process    = event_data.get("process_name", "Unknown")
        cmd        = event_data.get("command_line", "") or ""
        user       = event_data.get("user", "unknown")
        score      = event_data.get("anomaly_score", 0.0)
        severity   = event_data.get("severity", "normal").lower()
        techniques = self.mitre.get_attack_info(cmd)
        tech_text  = ", ".join(
            [f"{t['technique']} ({t['name']})" for t in techniques]
        ) if techniques else "None detected"

        if self.is_active:
            prompt = (
                "You are an advanced AI analyst in a Security Operations Center (SOC). "
                "Analyze the following endpoint telemetry event and produce a concise, "
                "professional forensic report in 4-5 sentences. Write in strict technical "
                "style. No greetings.\n\n"
                f"User:           {user}\n"
                f"Process:        {process}\n"
                f"Command line:   {cmd}\n"
                f"Threat level:   {severity.upper()}\n"
                f"ML Anomaly score: {score:.4f}\n"
                f"MITRE ATT&CK:   {tech_text}\n\n"
                "Explain what this activity is attempting, assess the risk level, "
                "and give one primary incident response recommendation."
            )
            try:
                response = self.client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=prompt,
                )
                return response.text
            except Exception:
                pass

        return self._generate_fallback_report(event_data)


# Singleton
ai_analyst = AIForensicEngine()
